### ISSUE TITLE
Gui is not displaying

### ISSUE THREAD

**Issue by kirantpatil** [evgeniy-khatko/tarantula#12]
Hi,

I installed the latest tarantula

I executed command "RAILS_ENV=production bundle exec rails s" 

I logged in with username and password 

Now Gui is not coming up

You may check our website at http://fossqc.patchbee.com:3000/

uname/password: admin/admin

Thanks.

**Comment by kirantpatil** [comment]
Also links in the page are not working. It is just displaying plain text static page.

**Comment by kirantpatil** [comment]
## Log content from Terminal:

Redirected to http://fossqc.patchbee.com:3000/home/login
Completed 302 Found in 7ms (ActiveRecord: 0.6ms)
Started GET "/home/login" for 106.51.81.216 at 2013-08-14 16:10:38 +0400
Processing by HomeController#login as HTML
  Rendered home/login.html.erb within layouts/application (1.6ms)
Completed 200 OK in 3ms (Views: 3.1ms | ActiveRecord: 0.0ms)
Started GET "/assets/application-0c97ba37a7d10857c0cde1192a9830dc.css" for 106.51.81.216 at 2013-08-14 16:10:38 +0400

ActionController::RoutingError (No route matches [GET] "/assets/application-0c97ba37a7d10857c0cde1192a9830dc.css"):
  actionpack (3.2.14) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.14) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.14) lib/rails/rack/logger.rb:18:in`call'
  actionpack (3.2.14) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.14) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.14) lib/rails/engine.rb:484:in `call'
  railties (3.2.14) lib/rails/application.rb:231:in`call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.14) lib/rails/rack/log_tailer.rb:17:in`call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

Started GET "/assets/application-e33c9f215675d7903413453f5a49df87.js" for 106.51.81.216 at 2013-08-14 16:10:38 +0400

ActionController::RoutingError (No route matches [GET] "/assets/application-e33c9f215675d7903413453f5a49df87.js"):
  actionpack (3.2.14) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.14) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.14) lib/rails/rack/logger.rb:18:in`call'
  actionpack (3.2.14) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.14) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.14) lib/rails/engine.rb:484:in `call'
  railties (3.2.14) lib/rails/application.rb:231:in`call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.14) lib/rails/rack/log_tailer.rb:17:in`call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

Started GET "/assets/tarantula/logo-2a4f4ef2d955f8474f7914309de05884.gif" for 106.51.81.216 at 2013-08-14 16:10:39 +0400

ActionController::RoutingError (No route matches [GET] "/assets/tarantula/logo-2a4f4ef2d955f8474f7914309de05884.gif"):
  actionpack (3.2.14) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.14) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.14) lib/rails/rack/logger.rb:18:in`call'
  actionpack (3.2.14) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.14) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.14) lib/rails/engine.rb:484:in `call'
  railties (3.2.14) lib/rails/application.rb:231:in`call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.14) lib/rails/rack/log_tailer.rb:17:in`call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

Started GET "/assets/tarantula/login_gradient-48898331366365178c5bcb052a889c6d.jpg" for 106.51.81.216 at 2013-08-14 16:10:39 +0400

ActionController::RoutingError (No route matches [GET] "/assets/tarantula/login_gradient-48898331366365178c5bcb052a889c6d.jpg"):
  actionpack (3.2.14) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.14) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.14) lib/rails/rack/logger.rb:18:in`call'
  actionpack (3.2.14) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.14) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.14) lib/rails/engine.rb:484:in `call'
  railties (3.2.14) lib/rails/application.rb:231:in`call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.14) lib/rails/rack/log_tailer.rb:17:in`call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

Started GET "/assets/tarantula/login_bg-ea40fe7eb83719f51b61c3058487e53c.jpg" for 106.51.81.216 at 2013-08-14 16:10:39 +0400

ActionController::RoutingError (No route matches [GET] "/assets/tarantula/login_bg-ea40fe7eb83719f51b61c3058487e53c.jpg"):
  actionpack (3.2.14) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.14) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.14) lib/rails/rack/logger.rb:18:in`call'
  actionpack (3.2.14) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.14) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.14) lib/rails/engine.rb:484:in `call'
  railties (3.2.14) lib/rails/application.rb:231:in`call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.14) lib/rails/rack/log_tailer.rb:17:in`call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

Started POST "/home/login" for 106.51.81.216 at 2013-08-14 16:10:50 +0400
Processing by HomeController#login as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"+q3hJIvE3hsLsZaCHK6X+EBdrHHGUAJdQUMEOTCVfP4=", "login"=>"admin", "password"=>"[FILTERED]", "commit"=>"Log in"}
  User Load (0.1ms)  SELECT `users`.\* FROM `users` WHERE `users`.`login` = 'admin' LIMIT 1
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
  Project Load (0.1ms)  SELECT `projects`.\* FROM `projects` 
  Project Load (0.1ms)  SELECT `projects`.\* FROM `projects` INNER JOIN `project_assignments` ON `projects`.`id` = `project_assignments`.`project_id` WHERE `project_assignments`.`user_id` = 1
  ProjectAssignment Load (0.1ms)  SELECT `project_assignments`.\* FROM `project_assignments` WHERE `project_assignments`.`user_id` = 1 AND `project_assignments`.`project_id` = 1 LIMIT 1
  Project Load (0.1ms)  SELECT `projects`.\* FROM `projects` WHERE `projects`.`id` = 1 LIMIT 1
Redirected to http://fossqc.patchbee.com:3000/
Completed 302 Found in 6ms (ActiveRecord: 0.6ms)
Started GET "/" for 106.51.81.216 at 2013-08-14 16:10:51 +0400
  User Load (0.1ms)  SELECT `users`.\* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
Processing by HomeController#index as HTML
  CACHE (0.0ms)  SELECT `users`.\* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
  Project Load (0.1ms)  SELECT `projects`.\* FROM `projects` 
  Project Load (0.1ms)  SELECT `projects`.\* FROM `projects` INNER JOIN `project_assignments` ON `projects`.`id` = `project_assignments`.`project_id` WHERE `project_assignments`.`user_id` = 1
  ProjectAssignment Load (0.1ms)  SELECT `project_assignments`.\* FROM `project_assignments` WHERE `project_assignments`.`user_id` = 1 AND `project_assignments`.`project_id` = 1 LIMIT 1
  Project Load (0.1ms)  SELECT `projects`.\* FROM `projects` WHERE `projects`.`id` = 1 LIMIT 1
  Rendered home/index.html.erb within layouts/inside (0.0ms)
Completed 200 OK in 7ms (Views: 2.1ms | ActiveRecord: 0.4ms)
Started GET "/assets/application-0c97ba37a7d10857c0cde1192a9830dc.css" for 106.51.81.216 at 2013-08-14 16:10:51 +0400

ActionController::RoutingError (No route matches [GET] "/assets/application-0c97ba37a7d10857c0cde1192a9830dc.css"):
  actionpack (3.2.14) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.14) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.14) lib/rails/rack/logger.rb:18:in`call'
  actionpack (3.2.14) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.14) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.14) lib/rails/engine.rb:484:in `call'
  railties (3.2.14) lib/rails/application.rb:231:in`call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.14) lib/rails/rack/log_tailer.rb:17:in`call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

Started GET "/assets/application-e33c9f215675d7903413453f5a49df87.js" for 106.51.81.216 at 2013-08-14 16:10:51 +0400

ActionController::RoutingError (No route matches [GET] "/assets/application-e33c9f215675d7903413453f5a49df87.js"):
  actionpack (3.2.14) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.14) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.14) lib/rails/rack/logger.rb:18:in`call'
  actionpack (3.2.14) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.14) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.14) lib/rails/engine.rb:484:in `call'
  railties (3.2.14) lib/rails/application.rb:231:in`call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.14) lib/rails/rack/log_tailer.rb:17:in`call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

Started GET "/assets/testia/bad_network-98c454793691f29ea46ea0ed26fe4354.gif" for 106.51.81.216 at 2013-08-14 16:10:52 +0400

ActionController::RoutingError (No route matches [GET] "/assets/testia/bad_network-98c454793691f29ea46ea0ed26fe4354.gif"):
  actionpack (3.2.14) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.14) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.14) lib/rails/rack/logger.rb:18:in`call'
  actionpack (3.2.14) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.14) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.14) lib/rails/engine.rb:484:in `call'
  railties (3.2.14) lib/rails/application.rb:231:in`call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.14) lib/rails/rack/log_tailer.rb:17:in`call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

Started GET "/assets/loading-6cf5bc8ec45739f458fb86f5dff3d36f.gif" for 106.51.81.216 at 2013-08-14 16:10:52 +0400

ActionController::RoutingError (No route matches [GET] "/assets/loading-6cf5bc8ec45739f458fb86f5dff3d36f.gif"):
  actionpack (3.2.14) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.14) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.14) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.14) lib/rails/rack/logger.rb:18:in`call'
  actionpack (3.2.14) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.14) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.14) lib/rails/engine.rb:484:in `call'
  railties (3.2.14) lib/rails/application.rb:231:in`call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.14) lib/rails/rack/log_tailer.rb:17:in`call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /home/fossqc/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

**Comment by kirantpatil** [comment]
With Puma server it is displaying the gui.
